#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROXY_PROJECT="mqtt-dev-proxy"
PROXY_NETWORK="mqtt-dev-proxy"

echo "==> Preparing dev environment setup..."

# 1. Clean up invalid directories created by docker-compose mounts if present
if [ -d "$SCRIPT_DIR/mosquitto/passwd/passwd" ]; then
    echo "Cleaning up directory created by Docker at docker/dev/mosquitto/passwd/passwd..."
    rm -rf "$SCRIPT_DIR/mosquitto/passwd/passwd"
fi

# 2. Setup password file if missing or empty
if [ ! -s "$SCRIPT_DIR/mosquitto/passwd/passwd" ]; then
    echo "==> Generating Mosquitto password file (testuser / testpass)..."
    chmod +x "$SCRIPT_DIR/mosquitto/passwd/setup-passwd.sh"
    "$SCRIPT_DIR/mosquitto/passwd/setup-passwd.sh"
fi

if [ -f "$SCRIPT_DIR/mosquitto/passwd/passwd" ]; then
    chmod 0600 "$SCRIPT_DIR/mosquitto/passwd/passwd" || true
fi

# 3. Setup TLS certificates if missing
if [ ! -f "$SCRIPT_DIR/mosquitto/certs/ca.crt" ]; then
    echo "==> Generating dev TLS certificates..."
    chmod +x "$SCRIPT_DIR/mosquitto/certs/generate.sh"
    "$SCRIPT_DIR/mosquitto/certs/generate.sh"
fi

# 4. Derive this worktree's identity
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
MESSAGE=$(git log -1 --pretty=%s 2>/dev/null || echo "")
WORKTREE=$(basename "$(git rev-parse --show-toplevel 2>/dev/null || pwd)")

# Slug: lowercase, non-alphanumerics collapsed to single dashes, trimmed
SLUG=$(echo "$WORKTREE" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9-]/-/g' -e 's/-\{2,\}/-/g' -e 's/^-//' -e 's/-$//')
[ -n "$SLUG" ] || SLUG="mqtt-dashboard"
DEV_HOST="$SLUG.localhost"
DEV_PROXY_PORT="${DEV_PROXY_PORT:-80}"
DEV_URL="http://$DEV_HOST"
[ "$DEV_PROXY_PORT" = "80" ] || DEV_URL="http://$DEV_HOST:$DEV_PROXY_PORT"

# 5. Write the per-worktree Compose env (auto-loaded from the compose file's dir)
cat > "$SCRIPT_DIR/.env" <<EOF
# Generated by docker/dev/setup-dev-env.sh — do not edit, do not commit.
COMPOSE_PROJECT_NAME=mqttdash-$SLUG
WORKTREE_SLUG=$SLUG
DEV_HOST=$DEV_HOST
DEV_URL=$DEV_URL
DEV_PROXY_PORT=$DEV_PROXY_PORT
EOF

# 6. Shared reverse proxy: network + container, both idempotent
if ! docker network inspect "$PROXY_NETWORK" >/dev/null 2>&1; then
    echo "==> Creating shared proxy network $PROXY_NETWORK..."
    docker network create "$PROXY_NETWORK" >/dev/null
fi

if [ -z "$(docker ps --quiet --filter "name=^${PROXY_PROJECT}$")" ]; then
    echo "==> Starting shared dev proxy (Traefik) on port $DEV_PROXY_PORT..."
    DEV_PROXY_PORT="$DEV_PROXY_PORT" docker compose -p "$PROXY_PROJECT" \
        -f "$SCRIPT_DIR/proxy/docker-compose-proxy.yml" up -d
fi

# 7. Generate worktree info for the frontend dev badge
TARGET_FILE="$(cd "$SCRIPT_DIR/../.." && pwd)/frontend/src/worktreeInfo.json"

node -e '
const fs = require("fs");
const [, target, worktree, branch, commit, message, url] = process.argv;
fs.writeFileSync(target, JSON.stringify({ worktree, branch, commit, message, url }, null, 2) + "\n");
' "$TARGET_FILE" "$WORKTREE" "$BRANCH" "$COMMIT" "$MESSAGE" "$DEV_URL" 2>/dev/null || true

echo "==> Dev environment setup complete!"
echo "==> This worktree will be served at $DEV_URL"
